# Generated by Django 5.2.3 on 2025-06-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="BroadGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=250)),
                ("preview_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="spotify_integration.album",
                    ),
                ),
                (
                    "artists",
                    models.ManyToManyField(
                        related_name="songs", to="spotify_integration.artist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecificGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "broad_genres",
                    models.ManyToManyField(
                        related_name="specific_genres",
                        to="spotify_integration.broadgenre",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artist",
            name="genres",
            field=models.ManyToManyField(
                related_name="artists", to="spotify_integration.specificgenre"
            ),
        ),
    ]
