# Generated by Django 5.2.3 on 2025-06-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="genres",
            field=models.ManyToManyField(
                related_name="artists_link", to="spotify_integration.specificgenre"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs_on_album",
                to="spotify_integration.album",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="artists",
            field=models.ManyToManyField(
                related_name="songs_link", to="spotify_integration.artist"
            ),
        ),
        migrations.AlterField(
            model_name="specificgenre",
            name="broad_genres",
            field=models.ManyToManyField(
                related_name="specific_genres_link", to="spotify_integration.broadgenre"
            ),
        ),
    ]
