# Generated by Django 5.2.4 on 2025-07-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_integration", "0002_alter_artist_genres_alter_song_album_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="user_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
