# Generated by Django 5.2.4 on 2025-09-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_integration", "0003_song_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expires_at", models.DateTimeField()),
            ],
        ),
    ]
