BROAD_GENRE_MAPPING = {
    "Rock": [
        "acid rock",
        "alt country",
        "alternative rock",
        "aor",
        "art rock",
        "britpop",
        "celtic rock",
        "christian alternative rock",
        "christian rock",
        "classic rock",
        "country rock",
        "funk rock",
        "glam rock",
        "garage rock",
        "grunge",
        "hard rock",
        "indie rock",
        "j-rock",
        "math rock",
        "neo-psychedelic",
        "nu metal",
        "pop punk",
        "post-grunge",
        "post-hardcore",
        "post-rock",
        "progressive rock",
        "proto-punk",
        "psychedelic rock",
        "punk",
        "rap rock",
        "rock",
        "rock and roll",
        "roots rock",
        "screamo",
        "shoegaze",
        "soft rock",
        "southern rock",
        "stoner rock",
        "visual kei",
        "yacht rock",
    ],
    "Pop": [
        "acoustic pop",
        "adult standards",
        "afropop",
        "alt-pop",
        "anime",
        "art pop",
        "bangla pop",
        "baroque pop",
        "bedroom pop",
        "c-pop",
        "canzone napoletana",
        "christian pop",
        "city pop",
        "country pop",
        "dream pop",
        "eurodance",
        "europop",
        "folk pop",
        "glitch",
        "gufeng",
        "gujarati pop",
        "harana",
        "haryanvi pop",
        "hindi pop",
        "hyperpop",
        "indie pop",
        "indonesian pop",
        "j-pop",
        "kayokyoku",
        "k-pop",
        "kannada pop",
        "kollywood",
        "kundiman",
        "lo-fi",
        "malayalam pop",
        "mandopop",
        "marathi pop",
        "moroccan pop",
        "new wave",
        "nightcore",
        "norwegian pop",
        "opm",
        "p-pop",
        "pinoy indie",
        "pop",
        "pop country",
        "punjabi pop",
        "soft pop",
        "synthpop",
        "t-pop",
        "taiwanese pop",
        "telugu pop",
        "thai indie pop",
        "thai pop",
        "tollywood",
        "v-pop",
        "variété française",
        "vocaloid",
    ],
    "Hip Hop / Rap": [
        "anime rap",
        "brooklyn drill",
        "chinese hip hop",
        "cloud rap",
        "crunk",
        "desi hip hop",
        "drill",
        "east coast hip hop",
        "g-funk",
        "gangster rap",
        "grime",
        "hardcore hip hop",
        "hindi hip hop",
        "hip hop",
        "horrorcore",
        "hyphy",
        "j-rap",
        "k-rap",
        "latin hip hop",
        "malayalam hip hop",
        "melodic rap",
        "mexican hip hop",
        "new york drill",
        "old school hip hop",
        "phonk",
        "rage rap",
        "rap",
        "rap metal",
        "rap rock",
        "southern hip hop",
        "tamil hip hop",
        "thai hip hop",
        "thai trap",
        "trap",
        "trap latino",
        "trap metal",
        "turkish hip hop",
        "uk drill",
        "uk grime",
        "underground hip hop",
        "west coast hip hop",
    ],
    "Electronic / Dance": [
        "afro house",
        "ambient",
        "alternative dance",
        "big beat",
        "big room",
        "breakbeat",
        "dark ambient",
        "deathstep",
        "disco",
        "drift phonk",
        "dubstep",
        "edm",
        "edm trap",
        "electro",
        "electro house",
        "electronic",
        "electronica",
        "eurodance",
        "future bass",
        "future house",
        "french house",
        "glitch",
        "hardcore techno",
        "hardstyle",
        "house",
        "idm",
        "italo dance",
        "jersey club",
        "liquid funk",
        "madchester",
        "melodic bass",
        "moombahton",
        "new age",
        "progressive house",
        "psytrance",
        "slap house",
        "stutter house",
        "synthwave",
        "tamil dance",
        "trance",
        "tropical house",
        "vinahouse",
    ],
    "R&B / Soul": [
        "afro r&b",
        "afro soul",
        "alternative r&b",
        "classic soul",
        "dark r&b",
        "doo-wop",
        "gospel r&b",
        "j-r&b",
        "latin r&b",
        "motown",
        "neo soul",
        "new jack swing",
        "pinoy r&b",
        "qawwali",
        "quiet storm",
        "r&b",
        "soul",
        "soul blues",
        "soul jazz",
        "trap soul",
        "worship",
    ],
    "Metal": [
        "alternative metal",
        "doom metal",
        "folk metal",
        "glam metal",
        "groove metal",
        "heavy metal",
        "metal",
        "metalcore",
        "nu metal",
        "symphonic metal",
        "thrash metal",
        "trap metal",
    ],
    "Country / Folk": [
        "acoustic country",
        "alt country",
        "country",
        "classic country",
        "folk",
        "folk pop",
        "folk rock",
        "outlaw country",
        "pop country",
        "roots rock",
        "singer-songwriter",
        "southern gothic",
        "traditional folk",
    ],
    "Jazz / Blues": [
        "big band",
        "blues",
        "boogie-woogie",
        "free jazz",
        "french jazz",
        "jazz",
        "jazz blues",
        "jazz rap",
        "smooth jazz",
        "soul jazz",
        "swing music",
        "vocal jazz",
    ],
    "World": [
        "afrobeat",
        "afrobeats",
        "afropiano",
        "afropop",
        "afroswing",
        "bachata",
        "bangla pop",
        "bhangra",
        "bollywood",
        "c-pop",
        "canzone napoletana",
        "chinese hip hop",
        "chinese indie",
        "chinese r&b",
        "chinese rock",
        "desi",
        "desi hip hop",
        "desi pop",
        "ghazal",
        "gufeng",
        "gujarati garba",
        "gujarati pop",
        "harana",
        "haryanvi pop",
        "hindi hip hop",
        "hindi indie",
        "hindi pop",
        "indonesian indie",
        "indonesian pop",
        "j-pop",
        "j-r&b",
        "j-rap",
        "j-rock",
        "japanese indie",
        "k-ballad",
        "k-pop",
        "k-rap",
        "k-rock",
        "kannada pop",
        "kayokyoku",
        "kollywood",
        "kundiman",
        "latin",
        "latin hip hop",
        "latin r&b",
        "malayalam hip hop",
        "malayalam pop",
        "mandopop",
        "marathi pop",
        "mexican hip hop",
        "mollywood",
        "moroccan pop",
        "opm",
        "p-pop",
        "pinoy indie",
        "pinoy r&b",
        "punjabi pop",
        "qawwali",
        "reggaeton",
        "reggaeton mexa",
        "sandalwood",
        "spanish-language reggae",
        "sufi",
        "t-pop",
        "taiwanese indie",
        "taiwanese pop",
        "tamil dance",
        "tamil hip hop",
        "tamil indie",
        "tamil pop",
        "telugu pop",
        "thai hip hop",
        "thai indie pop",
        "thai pop",
        "thai trap",
        "tollywood",
        "turkish hip hop",
        "urbano latino",
        "v-pop",
        "variété française",
        "vinahouse",
    ],
    "Classical / Ambient": [
        "ambient",
        "chamber music",
        "choral",
        "classical",
        "classical piano",
        "dark ambient",
        "devotional",
        "gregorian chant",
        "medieval",
        "minimalism",
        "neoclassical",
        "new age",
        "opera",
        "orchestra",
        "requiem",
    ],
    "Soundtrack / Musical": [
        "musicals",
        "soundtrack",
        "japanese vgm",
    ],
    "Indie": [
        "chinese indie",
        "german indie",
        "hindi indie",
        "indie",
        "indie folk",
        "indie pop",
        "indie rock",
        "indonesian indie",
        "jangle pop",
        "japanese indie",
        "pinoy indie",
        "taiwanese indie",
        "tamil indie",
        "thai indie pop",
    ],
    "Miscellaneous": [
        "emo",
        "noise music",
        "shibuya-kei",
    ],
}


def map_specific_genres_to_broad(specific_genres):
    """
    Maps a list of specific Spotify genres to a list of broad genres
    using the BROAD_GENRE_MAPPING.
    """
    broad_genres = set()
    # converting specific genres to lowercase for case-insensitive matching
    specific_genres_lower = [g.lower() for g in specific_genres]

    # Iterate through the BROAD_GENRE_MAPPING
    for broad_category, specific_genre_list in BROAD_GENRE_MAPPING.items():
        # check for existing specific genres in the broad category list
        normalized_specific_genre_list = [g.lower() for g in specific_genre_list]

        for sg in specific_genres_lower:
            if sg in normalized_specific_genre_list:
                broad_genres.add(broad_category)
                # move on if it already exists
                break
    return sorted(list(broad_genres))
